language: scala
scala:
- 2.12.2
script:
- sbt clean coverage test coverageReport
after_success:
- sbt coveralls
deploy:
  provider: heroku
  api_key:
    secure: aaGTa+Z0hF2sR+UQVk5XasPN8ArAI0bAwWXSvDLCxdYZm7rt/IHIK7FgRVjHflTasBBAnOiCZbOMG9otZrXX9Y1DdyBJhwwdQSmTgLktICSrvEViL0fA1/Pr6G7Zift2VIgAvUM3CUem/D9CGGtIDRffyA6YG8p8PXJ+zd349AfPsVxITMyev50jUIEXcHo06H1lgMxgypt8L9dyUoTvBgJopldPZDU9I0WV2GYstJM3bsQf96N6KT270XwLIc8OvAn9UUocq1Kti2m9OtyJDBqN1nFRu/2tcQ1EJdi6t8lTXaSrCbKov8eoBa8bz7Iqt7bK3XNWQfxXVqhTwHnAzt1Nzl0OlNVve/nnHu5iJCFIK6ni+HZzDf8IyURLWxqsju+PHc3JLS+ooOaYRxbsuIbHNPFzwWuMHYsIgXGYg07jzHUEbrK870PHhN1farWkX5XIUQV7MbkN9BxYCPBnOK/Kl1MtCVo4DhNeD1Eib50oW3BFPdCiiOxwi085aXxWyfSq79nZSZxego+fTACbCADRh1B/uvycbflCbt9zbJjGc6VOyRq81acPjDgwrFSRxpblKAFG8NeIi8DEoteuFVjZ4Rn0SezMXMJlftpDwsKTA60OyV+WDj9xuyixt9wBMpmTlhY+/GrSRWNxuYCORV2cR17UgnkaY21pCW9g4NQ=
  app: play-rest-service
  on:
    repo: alexm118/play-rest-service
