version: '2'
services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "9000:9000"
#    stdin_open: true
  postgres:
    image: postgres:9.6.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: play-db